packages:
  - 'packages/*'

catalog:
  '@types/node': ^20.10.0
  '@typescript-eslint/eslint-plugin': ^7.0.0
  '@typescript-eslint/parser': ^7.0.0
  esbuild: ^0.19.8
  eslint: ^8.57.0
  eslint-config-airbnb-base: ^15.0.0
  eslint-config-airbnb-typescript: ^18.0.0
  eslint-import-resolver-typescript: ^3.6.0
  eslint-plugin-import: ^2.29.0
  tsx: ^4.20.5
  typescript: ~5.5.4